/**
 * Ações que podem ser auditadas no sistema
 */
export enum AuditAction {
  // Ações CRUD
  CREATE = 'CREATE',
  READ = 'READ',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
  RESTORE = 'RESTORE',

  // Ações de Sistema
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  FAILED_LOGIN = 'FAILED_LOGIN',
  PASSWORD_RESET = 'PASSWORD_RESET',
  EXPORT = 'EXPORT',
  IMPORT = 'IMPORT',

  // Ações de Negócio
  AVERBACAO = 'AVERBACAO',
  MARGEM_BLOQUEIO = 'MARGEM_BLOQUEIO',
  MARGEM_LIBERACAO = 'MARGEM_LIBERACAO',
  CONTRATO_LIQUIDACAO = 'CONTRATO_LIQUIDACAO',
  CONTRATO_FINALIZACAO = 'CONTRATO_FINALIZACAO',
  
  // Ações de Configuração
  CONFIG_UPDATE = 'CONFIG_UPDATE',
  PERMISSION_UPDATE = 'PERMISSION_UPDATE',
  INTEGRATION_UPDATE = 'INTEGRATION_UPDATE',
}
