/**
 * Eventos que podem gerar notificações
 */
export enum NotificationEvent {
  // Eventos de Contrato
  CONTRATO_CRIADO = 'CONTRATO_CRIADO',
  CONTRATO_AVERBADO = 'CONTRATO_AVERBADO',
  CONTRATO_REJEITADO = 'CONTRATO_REJEITADO',
  CONTRATO_LIQUIDADO = 'CONTRATO_LIQUIDADO',
  CONTRATO_FINALIZADO = 'CONTRATO_FINALIZADO',

  // Eventos de Margem
  MARGEM_ATUALIZADA = 'MARGEM_ATUALIZADA',
  MARGEM_BLOQUEADA = 'MARGEM_BLOQUEADA',
  MARGEM_LIBERADA = 'MARGEM_LIBERADA',

  // Eventos de Folha
  FOLHA_IMPORTADA = 'FOLHA_IMPORTADA',
  FOLHA_PROCESSADA = 'FOLHA_PROCESSADA',
  FOLHA_ERRO = 'FOLHA_ERRO',

  // Eventos de Sistema
  USUARIO_CRIADO = 'USUARIO_CRIADO',
  USUARIO_BLOQUEADO = 'USUARIO_BLOQUEADO',
  SENHA_REDEFINIDA = 'SENHA_REDEFINIDA',
  ACESSO_SUSPEITO = 'ACESSO_SUSPEITO',

  // Eventos de Relatório
  RELATORIO_GERADO = 'RELATORIO_GERADO',
  RELATORIO_ERRO = 'RELATORIO_ERRO',

  // Eventos de Integração
  INTEGRACAO_ERRO = 'INTEGRACAO_ERRO',
  INTEGRACAO_TIMEOUT = 'INTEGRACAO_TIMEOUT',
}
