export enum ProdutoGrupo {
  EMPRESTIMOS = 1,
  MENSALIDADES = 7
}

export enum ProdutoTipo {
  PRAZO_DETERMINADO_PARCELA_FIXA = 1,
  PRAZO_INDETERMINADO_PARCELA_FIXA = 2,
  PRAZO_INDETERMINADO_PARCELA_VARIAVEL = 3
}
