export enum SolicitacaoSituacao {
  CANCELADO = 0,
  PENDENTE = 1,
  PROCESSADA = 2,
  EM_ANALISE = 3,
  REDIRECIONADA = 4,
  REJEITADA = 5
}

export enum SolicitacaoTipo {
  INFORMAR_SALDO_DEVEDOR = 1,
  INFORMAR_QUITACAO = 2,
  CONFIRMAR_REJEITAR_QUITACAO = 3,
  CONCLUIR_COMPRA_DIVIDA = 4,
  APROVAR_AVERBACOES = 5,
  DESLIQUIDAR_AVERBACOES = 6,
  CANCELAR_AVERBACOES = 7,
  INFORMAR_PESSOAS_CONTATO = 8,
  HOMOLOGAR_AVERBACOES = 9,
  ACOMPANHAR_CLIENTES = 10,
  APROVAR_RESERVA_SIMULACAO = 11,
  REGULARIZAR_QUITACAO_REJEITADA = 12,
  OUVIDORIA = 13,
  ACOMPANHAR_AVERBACAO_SEM_PRIMEIRO_DESCONTO = 14,
  MINHAS_SOLICITACOES_COMPRA_AGUARDANDO_SALDO = 15,
  MINHAS_SOLICITACOES_COMPRA_AGUARDANDO_LIQUIDACAO = 16,
  SOLICITACAO_INFORMACAO = 17,
  SOLICITACAO_EMPRESTIMO = 18
}
